### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by yaskor** [appleboy/drone-git-push#28]
I have problems with the key parameter.

I would like to write the key directly into the yaml but I do not know in which format 
(line breaks ?, private + public, only private).

**Comment by boredland** [comment]
I have the same problem.

**Comment by appleboy** [comment]
only private. try the following command.

```
$ drone secret add --name git_push_ssh_key --value @/xxxxx/teabot_id_rsa --event push --image appleboy/drone-git-push go-gitea/gitea
```
