### ISSUE TITLE
Load key: invalid format

### ISSUE THREAD

**Issue by xoxys** [appleboy/drone-git-push#34]
I always got:
```
Warning: Permanently added 'gitea.example.com' (ECDSA) to the list of known hosts.
Load key "/root/.ssh/id_rsa": invalid format
Permission denied (publickey).
fatal: Could not read from remote repository.
```
ssh and git push from a shell works without problems. Any suggestions? I don't know what I'm doing wrong.

**Comment by xoxys** [comment]
Import key with drone cli to secrets fixed this issue

**Comment by dschmidt** [comment]
I stumbled upon this when trying to test my pipeline locally in `drone exec`. 

FTR: When setting this in your secret file, you need to use a quoted string and replace newlines with `\n`. It should look like this:
```bash
ssh_key="-----BEGIN RSA PRIVATE KEY-----\nfoo\n\bar\ndoo\n-----END RSA PRIVATE KEY-----"
```
This is currently the only way to have new lines in godotenv which drone cli uses.

**Comment by mco-system** [comment]
Quick command line to replace all EOL by "\n" char sequence:
`sed ':b;N;$!bb;s/\n/\\n/g' /my/private/ssh_key`

You also need this when creating a secret from a ssh private key via the web interface.

**Comment by esturniolo** [comment]
Another solution it's use an `echo -e $PRIVATE_KEY > /your/path/id_rsa` in the command section.
`echo` only don't work. `echo -e` yes.
