### ISSUE TITLE
[help request] the commiter's message looks wrong

### ISSUE THREAD

**Issue by a1012112796** [appleboy/drone-git-push#52]
Hello, I found that in [gitea](https://github.com/go-gitea/gitea), the commiter of the commit pushed by this plugin looks wrong. would you please help check it? Thanks!

https://drone.gitea.io/go-gitea/gitea/56106/1/4
![image](https://user-images.githubusercontent.com/25342410/173726330-f3a3583d-fb7f-4315-80a0-eb0008a396c4.png)

https://github.com/go-gitea/gitea/blob/main/.drone.yml#L536-L548
![image](https://user-images.githubusercontent.com/25342410/173726523-d4b164c1-7c5b-4259-b330-89588a733d38.png)

https://github.com/go-gitea/gitea/commit/f6e2dbaf1e079308b0739e9a74f165257ea6171d
![image](https://user-images.githubusercontent.com/25342410/173726745-4ba3b595-991a-46e7-adcf-d23532bd775b.png)

**Comment by lcomrade** [comment]
I have the same problem. The `author_name` and `author_email` are ignored.

**Comment by appleboy** [comment]
fix in https://github.com/appleboy/drone-git-push/pull/59
