### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by garymoon** [appleboy/drone-git-push#63]
This repo is affected by the `exec /bin/drone-git-push: exec format error` message for those using `:latest` on x86_64 because latest is tagged for arm64 only.

See [here](https://github.com/appleboy/drone-ssh/issues/218) and [here](https://github.com/appleboy/drone-scp/issues/146) for issues on drone-ssh and drone-scp respectively.

**Comment by garymoon** [comment]
For now you can either use `appleboy/drone-git-push:0.2.2` to pin the last release with an amd64 image, or use `appleboy/drone-git-push:linux-amd64` for the latest available amd64 image.

**Comment by theautomation** [comment]
Thanks for the solution. I have added ```:linux-amd64``` tag and it is working again.

**Comment by appleboy** [comment]
@garymoon Fixed. Please try the latest tag.

**Comment by garymoon** [comment]
I can confirm this is fixed, thanks @appleboy!
