### ISSUE TITLE
error: unknown switch `='

### ISSUE THREAD

**Issue by theautomation** [appleboy/drone-git-push#64]
Hi, getting this error in my drone ci pipeline. I think it has something to do with the author key value. Any idea how to fix this? 

```console
+ git add --all
+ git diff-index --quiet HEAD --ignore-submodules
+ git commit -m [bot] [skip ci] bump image tag -a=""theautomation" <"github@theautomation.nl">"
error: unknown switch `='
usage: git commit [<options>] [--] <pathspec>...
```

**Comment by 6543** [comment]
look's like an escape bug?

**Comment by JonasBernard** [comment]
I have the same issue.
I use the project like so:

- name: push
  image: appleboy/drone-git-push
  when:
    event:
      exclude:
      - promote
  settings:
    branch: master
    remote: git@github.com:JonasBernard/FakeStandby.git
    ssh_key:
      from_secret: GH_SSH_KEY
    force: false
    commit: true
    commit_message: "Auto-imported translations from PoEditor and updated CONTRIBUTING.MD"
    author_name: Drone Pipeline

**Comment by JonasBernard** [comment]
> It is working in `0.2.2` but broken in `1.0.0`
> 
> Here is my yaml of the pipeline step, can't see any weird escaping. Also tried with single quotes around commit message value but didn't work either.
> 
> ```yaml
>   [...]
>   - name: push k8s manifest
>     image: jonasbernard/drone-git-push:1-linux-amd64
>     [...]
> ```

You can use my folk or wait for my fix to be merged.
Just remember to switch back to `appleboy/drone-git-push` as I will not maintain my folk actively.

Hope this helps. Regards.
