### ISSUE TITLE
[Woodpecker CI] Skip commits flag does not work

### ISSUE THREAD

**Issue by lambdaclan** [appleboy/drone-git-push#83]
Hello there,

Thank you very much for developing this plugin. It is quite useful for doing automatic version bumps when dependencies are updated with tools like renovate. 

I have more or less integrated the plugin into my workflow and everything is working as expected except from the fact that a push via the plugin always cancels the running workflow and triggers a new one on Woodpecker CI.

According to the [documentation](https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#skip-commits) simply including `[skip ci]` or `[ci skip]` should prevent a new workflow from starting while keeping the ongoing one running.

I can confirm that this works when I manually push commits through the terminal but for whatever reason the message content gets ignored when a push is triggered via the plugin.

Does the plugin do anything special that requires special treatment? To be honest, I am not sure if this is an issue with the plugin or Woodpecker CI itself. If you think that this is likely a Woodpecker issue I will open a new issue on their repo as well.

**Comment by appleboy** [comment]
missing docs link and you should report to Woodpecker team
